# Generated by Django 5.2 on 2025-04-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_trainingdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdata',
            name='user_id',
        ),
    ]
